## define sprites

image aya = "side aya neutral.png"
#image define aya excited = "side aya excited.png"
#image define aya gloom = "side aya gloom.png"
#image define aya happy = "side aya happy.png"
#image define aya neutral = "side aya neutral.png"
#image define aya sad = "side aya sad.png"
#image define aya shocked = "side aya shocked.png"
#image define aya tsun = "side aya tsuntsun.png"

#image aya excited = "Aya Excited.png"
#image aya gloom = "Aya Gloom.png"
#image aya happy = "Aya Happy.png"
#image aya neutral = "Aya Neutral.png"
#image aya sad = "Aya Sad.png"
#image aya shocked = "Aya Shocked.png"
#image aya tsun = "Aya TsunTsun.png"

image erin = "erin neutral.png"
#image erin neutral = "erin neutral.png"
#image erin blush = "erin blush.png"
#image erin excited = "erin excited.png"
#image erin gloom = "erin gloom.png"
#image erin happy = "erin happy.png"
#image erin rizz = "erin rizzler.png"
#image erin sad = "erin sad.png"
#image erin shocked = "erin shocked.png"

##image erin blush = "Erin Blush.png"
#image erin excited = "Erin Excited.png"
#image erin gloom = "Erin Gloom.png"
#image erin happy = "Erin Happy.png"
#image erin neutral = "Erin Neutral.png"
#image erin rizz = "Erin Rizzler.png"
#image erin sad = "Erin Sad.png"
#image erin shocked = "Erin Shocked.png"

image jeff = "side jeff.png"
image timothy = "side timothy.png"


## define bgs

image bg bathroom = "bathroom.png"
image bg bedroom = "bedroom.png"
image bg bookstore = "bookstore.png"
image bg cornerstore = "cornerstore.png"
image bg gate = "gate.png"
image bg kitchen = "kitchen.png"
image bg lydias = "lydias.png"
image bg market = "market.png"
image bg nightmarket = "nightmarket.png"
image bg orchard = "orchard.png"
image bg rain = "rain.png"

image bg bathroom night = "bathroom night.png"
image bg bedroom night = "bedroom night.png"
image bg bookstore night = "bookstore night.png"
image bg cornerstore night = "cornerstore night.png"
image bg gate night = "gate night.png"
image bg kitchen night = "kitchen night.png"
image bg lydias night = "lydias night.png"
image bg market night = "market night.png"
image bg nightmarket night = "nightmarket night.png"
image bg orchard night = "orchard night.png"
image bg rain night = "rain night.png"

image bg nightmarket red = "nightmarket red.png"

image cg piggyback = "cg_piggyback.png"