
define audio.main = "music/Menu.flac"
define audio.bookstore_sunshine = "music/Hanging Around The Library.flac"
define audio.bookstore_vibing = "music/Hanging Around The Library (Lofi Variant).flac"
define audio.coffee = "music/Having Some Coffee.flac"
define audio.happy_village = "music/Passing Through the Cottages and Hills.flac"
define audio.quiet_village = "music/A Walk in The Park.flac"
define audio.rain_transition = "music/Something's Not Right.flac"
define audio.rain = "music/Sorrow.flac"
define audio.cornerstore = "music/Window Shopper.flac"
define audio.romance = "music/Citrus & Apples.flac"
define audio.spirit = "music/Amber Pact.flac"
define audio.credits = "music/Credits.flac"