
define audio.main = "music/Main Title.flac"
define audio.bookstore_sunshine = "music/Bookstore Sunshine.flac"
define audio.bookstore_vibing = "music/Bookstore Vibing.flac"
define audio.coffee = "music/Coffeeshop.flac"
define audio.happy_village = "music/Happy Village.flac"
define audio.quiet_village = "music/Quiet Village.flac"
define audio.rain_transition = "music/Rainy Day Transition.flac"
define audio.rain = "music/Rainy Day.flac"
define audio.cornerstore = "music/Cornerstore.flac"
define audio.romance = "music/Romance Lofi.flac"
define audio.spirit = "music/SpiritChase.flac"
define audio.credits = "music/Credits.flac"